icon: "app/src/main/ic_launcher-web.png"
googleplay: "https://play.google.com/store/apps/details?id=me.jfenn.smartAlarm"
package: "me.jfenn.smartAlarm"
screenshots:
  - ".github/images/home.png"
  - ".github/images/alarms.png"
  - ".github/images/timers.png"
  - ".github/images/themes.png"
  - ".github/images/alert.gif"